version: "3.6"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATADIR}/heimdall:/config
    container_name: heimdall
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - vlan20
    labels:
      my.zone: zone1
      traefik.enable: true
      traefik.http.routers.heimdall.rule: Host(`${SUB_DOMAIN}.${SERVER_DOMAIN}`)
      traefik.http.routers.heimdall.entrypoints: websecure
      traefik.http.services.heimdall.loadbalancer.server.port: 80

networks:
  vlan20:
    name: vlan20
    driver: macvlan
    driver_opts:
      parent: ens192.20
    ipam:
      config:
        - subnet: 192.168.20.0/24
          gateway: 192.168.20.1
  vlan10:
    name: vlan10
    driver: macvlan
    driver_opts:
      parent: ens192.10
    ipam:
      config:
        - subnet: 192.168.10.0/24
          gateway: 192.168.10.1
