---
- name: Setup docker .env file
  template:
    src: templates/dockerEnv.env
    dest: "../.env"

- name: Install the needed docker packages
  apt:
    name:
    - docker
    - docker-compose
    state: latest
    cache_valid_time: 3600

- name: Ensure docker group exists
  group:
    name: docker
    state: present

- name: Add user {{adminuser}} to docker group
  user:
    name: "{{adminuser}}"
    groups: docker
    append: yes

- name: Create folder for docker data
  file:
    path: "${DATADIR}"
    state: directory

- name: Create folder for traefik data
  file:
    path: "${DATADIR}/traefik/acme"
    state: directory

- name: Create acme config file for traefik
  file:
    path: "${DATADIR}/traefik/acme/acme.json"
    state: touch
    mode: '0600'

- name: Create the external docker network
  docker_network:
    name: traefik_proxy
