---
- name: Setup docker .env file
  template:
    src: templates/dockerEnv.env
    dest: "../.env"

- name: Create folder for docker data
  file:
    path: "${DATADIR}"
    state: directory

- name: Create folder for traefik data
  file:
    path: "${DATADIR}/traefik/acme"
    state: directory

- name: Create acme config file for traefik
  file:
    path: "${DATADIR}/traefik/acme/acme.json"
    state: touch
    mode: '0600'

- name: Create the external docker network
  docker_network:
    name: traefik_proxy

- name: Create a network with options
  docker_network:
    name: vlan20
    driver: macvlan
    driver_options:
       parent: ens192.20
    ipam_options:
       subnet: 192.168.20.0/24
       gateway: 192.168.20.1
  docker_network:
    name: vlan10
    driver: macvlan
    driver_options:
       parent: ens192.10
    ipam_options:
       subnet: 192.168.10.0/24
       gateway: 192.168.10.1
